# Development Dockerfile with Air hot reload
FROM golang:1.25-alpine

RUN apk add --no-cache build-base git

WORKDIR /app

RUN go install github.com/air-verse/air@latest

ENV CGO_ENABLED=1

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]

