// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/movies": {
            "get": {
                "description": "Returns a paginated list of movies, optionally filtered by query, year, genre and cursor.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "List and search movies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query for movie title substring",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Release year (YYYY) derived from releaseDate",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exact genre filter",
                        "name": "genre",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of items to return (default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor from previous page's nextCursor",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal.MoviePage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new movie and synchronously enriches it with box office data when available.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Create a new movie",
                "parameters": [
                    {
                        "description": "Movie to create",
                        "name": "movie",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal.MovieCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal.Movie"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "Location of the newly created movie resource"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/internal.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable entity (validation or invalid JSON)",
                        "schema": {
                            "$ref": "#/definitions/internal.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal.Error"
                        }
                    }
                }
            }
        },
        "/movies/{title}/rating": {
            "get": {
                "description": "Returns the average rating (rounded to one decimal) and count of ratings for the given movie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ratings"
                ],
                "summary": "Get rating aggregate for a movie",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Movie title",
                        "name": "title",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal.RatingAggregate"
                        }
                    },
                    "404": {
                        "description": "Movie not found or no ratings yet",
                        "schema": {
                            "$ref": "#/definitions/internal.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal.Error"
                        }
                    }
                }
            }
        },
        "/movies/{title}/ratings": {
            "post": {
                "security": [
                    {
                        "RaterId": []
                    }
                ],
                "description": "Submits a rating for the given movie title. If the rater has already rated this movie, the rating is updated.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ratings"
                ],
                "summary": "Submit or update a rating for a movie",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Movie title",
                        "name": "title",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique rater identifier",
                        "name": "X-Rater-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Rating payload (0.5-5.0 in 0.5 steps)",
                        "name": "rating",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal.RatingSubmit"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Rating updated",
                        "schema": {
                            "$ref": "#/definitions/internal.RatingResult"
                        }
                    },
                    "201": {
                        "description": "Rating created",
                        "schema": {
                            "$ref": "#/definitions/internal.RatingResult"
                        },
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "Location of the rating resource when created"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request (invalid body or rating)",
                        "schema": {
                            "$ref": "#/definitions/internal.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized (missing or invalid X-Rater-Id)",
                        "schema": {
                            "$ref": "#/definitions/internal.Error"
                        }
                    },
                    "404": {
                        "description": "Movie not found",
                        "schema": {
                            "$ref": "#/definitions/internal.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal.BoxOffice": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "lastUpdated": {
                    "type": "string"
                },
                "revenue": {
                    "$ref": "#/definitions/internal.Revenue"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "internal.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "internal.Movie": {
            "type": "object",
            "properties": {
                "boxOffice": {
                    "$ref": "#/definitions/internal.BoxOffice"
                },
                "budget": {
                    "type": "integer"
                },
                "distributor": {
                    "type": "string"
                },
                "genre": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mpaRating": {
                    "type": "string"
                },
                "releaseDate": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal.MovieCreate": {
            "type": "object",
            "properties": {
                "budget": {
                    "type": "integer"
                },
                "distributor": {
                    "type": "string"
                },
                "genre": {
                    "type": "string"
                },
                "mpaRating": {
                    "type": "string"
                },
                "releaseDate": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal.MoviePage": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal.Movie"
                    }
                },
                "nextCursor": {
                    "type": "string"
                }
            }
        },
        "internal.RatingAggregate": {
            "type": "object",
            "properties": {
                "average": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "internal.RatingResult": {
            "type": "object",
            "properties": {
                "movieTitle": {
                    "type": "string"
                },
                "raterId": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                }
            }
        },
        "internal.RatingSubmit": {
            "type": "object",
            "properties": {
                "rating": {
                    "type": "number"
                }
            }
        },
        "internal.Revenue": {
            "type": "object",
            "properties": {
                "openingWeekendUSA": {
                    "type": "integer"
                },
                "worldwide": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
